### PR TITLE
Feature/errorbar

### PR DESCRIPTION
**Pull request by chilijung**
@boygirl I've done errorbar implementation in react-native IOS. I still can't successfully start demo in my andriod simulator.

```
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:compileDebugJavaWithJavac
/Users/lijungchi/Documents/canner/victory-chart-native/demo/android/app/src/main/java/com/demo/MainActivity.java:34: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

do anyone know what happened in my andriod app? I've tried hard to solve it still no success :( .

BTW, I don't have the right to push directly to this repo, so I forked.

### CODE REVIEW

File: package.json [hunk 1]
```diff
@@ -20,13 +20,13 @@
   "scripts": {
     "start": "./node_modules/react-native/packager/packager.sh start --reset-cache --projectRoots `pwd`,`pwd`/demo"
   },
+  "peerDependencies": {
```
Comment (boygirl) [inline package.json]: Please leave this as a dev dependency for now

**Comment by boygirl** [comment]
@chilijung approved pending peer dependency change, and changing the git url to a real version once the supporting work in victory-chart is merged and released. :tada:

**Comment by boygirl** [comment]
@chilijung I've merged and published your work in victory-chart as version 10.1.0. You can change that dependency here and this should be ready to merge.
